### ISSUE TITLE
Error: Invalid memory access in Shell32.Shell_NotifyIcon

### ISSUE THREAD

**Issue by Nohus** [dorkbox/JNA#1]
I have crash reports from multiple users on Windows where `Shell_NotifyIcon` in `Shell32.java` crashes with `Error: Invalid memory access`. These happen both on Windows 10 and Windows 11, but I could not reproduce it myself.

**Comment by dorkbox** [comment]
Can you get me a stack trace? Also, more details about their OS? (64/32 bit specifically, although I think Win11 is only 64 bit, but I don’t remember)

**Comment by Nohus** [comment]
Stack trace:
```
java.lang.Error: Invalid memory access
    at dorkbox.jna.windows.Shell32.Shell_NotifyIcon(Shell32.java:0)
    at dorkbox.systemTray.ui.swing._WindowsNativeTray$1.setImage(_WindowsNativeTray.java:107)
    at dorkbox.systemTray.MenuItem.setImageFromTray(MenuItem.java:212)
    at dorkbox.systemTray.SystemTray.setImage(SystemTray.java:1082)
    at my application
```

I do not know the specific OS details other than it happens both on Windows 10 and Windows 11. I will try to get them.

**Comment by Nohus** [comment]
This is one system where the error happens:
Windows 11, build 10.0.22621.2861, 64 bit
